Don't auto tag if we choose the skip option

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -91,13 +91,21 @@ jobs:
 
       - name: Create Git tag and push
         run: |
-          new_tag=${{ steps.determine_next_tag.outputs.new_tag }}
-          new_version_num=${new_tag#v}
-          git tag -a "${new_tag}" -m "Version ${new_version_num}"
-          git push --tags origin "${new_tag}"
+          new_tag="${{ steps.determine_next_tag.outputs.new_tag }}"
+          new_tag=${new_tag#v}
+          new_tag=${new_tag%-*}
+
+          if [[ -z "${new_tag}" ]]; then
+            echo "Could not determine next tag";
+            exit 1;
+          elif [[ "${new_tag}" != 'Skip' ]]; then
+            git tag -a "${new_tag}" -m "Version ${new_version_num}"
+            git push --tags origin "${new_tag}"
+          fi
 
   release:
     needs: tag
+    if: ${{ needs.tag.outputs.new_tag != 'Skip' }}
     permissions:
       contents: write
     uses: climatepolicyradar/reusable-workflows/.github/workflows/release.yml@v3
